import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
 <link rel="icon" href="/favicon.ico" />


export const metadata: Metadata = {
  title: "Fraud Detection",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer />
        
      </body>
    </html>
  );
}
